apiVersion: apps/v1
kind: Deployment
metadata:
  name:  APIREST
  namespace: default
  labels:
    app:  APIREST
spec:
  selector:
    matchLabels:
      app: APIREST
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  APIREST
    spec:
      containers:
      - name:  APIREST
        image:  732629678930.dkr.ecr.us-east-1.amazonaws.com/mao-ecr-eks:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
          - containerPort:  8080
---
apiVersion: v1
kind: Service
metadata:
  name: APIREST
  namespace: devsecops
spec:
  selector:
    app: APIREST
  type: LoadBalancer
  ports:
    - name: APIREST
      protocol: TCP
      port: 80
      targetPort: 8080